apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: kallepan/pcr-oe-frontend
    newName: kallepan/pcr-oe-frontend
    newTag: IMAGE_TAG